In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import pbn_37k
from pbn_37k.ask import sigAssistant
from pptx import Presentation

import pandas as pd
from tqdm import tqdm
tqdm.pandas()

from dotenv import load_dotenv
load_dotenv()

from openai import OpenAI
import base64

from PIL import Image
import base64
from io import BytesIO
import os
from pptx import Presentation
import pandas as pd

client = OpenAI()


brain = sigAssistant(pathCache="../.cache/", llm_highend="gpt-4o",  llm_fast="gpt-4o-mini")

/home/kelu/projets/maptivity/.venv/lib/python3.11/site-packages/langchain/embeddings/cache.py:58: UserWarning: Using default key encoder: SHA-1 is *not* collision-resistant. While acceptable for most cache scenarios, a motivated attacker can craft two different payloads that map to the same cache key. If that risk matters in your environment, supply a stronger encoder (e.g. SHA-256 or BLAKE2) via the `key_encoder` argument. If you change the key encoder, consider also creating a new cache, to avoid (the potential for) collisions with existing keys.
  _warn_about_sha1_encoder()

In [4]:


def load_sheet(file_path,sheetname=""):
    """
    Lists all sheet names in an Excel file, then loads the second one as a DataFrame.
    
    Parameters:
        file_path (str): Path to the Excel file.
    
    Returns:
        tuple: (sheet_names, df) where
            - sheet_names is a list of all sheet names
            - df is the DataFrame of the second sheet (or None if less than 2 sheets)
    """
    # Create an ExcelFile object to inspect sheets
    xls = pd.ExcelFile(file_path)
    
    # Get list of all sheet names
    sheet_names = xls.sheet_names
    print("Sheet names found:", sheet_names)
    try:
        # Load the second sheet into a DataFrame
        df = pd.read_excel(xls, sheet_name=sheetname)
        print(f"Loaded second sheet: {sheetname}")
    except:
        return None
    return df

In [5]:
dfs = []
for city in ['SHIRE', 'GOTHAM CITY', 'HOGSMEADE']:
    df = load_sheet("Maptivity_Cards.xlsx","SHIRE")
    df["city"]=city
    dfs.append(df)
dfs = pd.concat(dfs).reset_index(drop=True)
dfs["ID"] = dfs["city"]+"_"+dfs.index.astype(str)
dfs

Sheet names found: ['Instructions', 'ENLIT TOTAL', 'SHIRE', 'GOTHAM CITY', 'HOGSMEADE']
Loaded second sheet: SHIRE
Sheet names found: ['Instructions', 'ENLIT TOTAL', 'SHIRE', 'GOTHAM CITY', 'HOGSMEADE']
Loaded second sheet: SHIRE
Sheet names found: ['Instructions', 'ENLIT TOTAL', 'SHIRE', 'GOTHAM CITY', 'HOGSMEADE']
Loaded second sheet: SHIRE

,Project,Title,Text,city,ID
0,PROBONO,CERNA Assessment,The neighbourhood is exploring a new approach ...,SHIRE,SHIRE_0
1,PROBONO,Green Roof,The town's skyline is set to become greener as...,SHIRE,SHIRE_1
2,CHRONICLE,Renovation planner,A digital tool that suports decision-making fo...,SHIRE,SHIRE_2
3,FORTESIE,Energy savings at municipal swimming pool,The municipal swimming pool has reopened after...,SHIRE,SHIRE_3
4,FORTESIE,Better air quality at schools,"At a school, air quality has quietly become pa...",SHIRE,SHIRE_4
5,EFORT,SecureBox in the Village Microgrid,A storm-prone rural community pilots a SecureB...,SHIRE,SHIRE_5
6,REEFLEX,The Digital Twin for Flexibility Empowerment,The local energy community is piloting a digit...,SHIRE,SHIRE_6
7,PROBONO,CERNA Assessment,The neighbourhood is exploring a new approach ...,GOTHAM CITY,GOTHAM CITY_7
8,PROBONO,Green Roof,The town's skyline is set to become greener as...,GOTHAM CITY,GOTHAM CITY_8
9,CHRONICLE,Renovation planner,A digital tool that suports decision-making fo...,GOTHAM CITY,GOTHAM CITY_9
10,FORTESIE,Energy savings at municipal swimming pool,The municipal swimming pool has reopened after...,GOTHAM CITY,GOTHAM CITY_10
11,FORTESIE,Better air quality at schools,"At a school, air quality has quietly become pa...",GOTHAM CITY,GOTHAM CITY_11
12,EFORT,SecureBox in the Village Microgrid,A storm-prone rural community pilots a SecureB...,GOTHAM CITY,GOTHAM CITY_12
13,REEFLEX,The Digital Twin for Flexibility Empowerment,The local energy community is piloting a digit...,GOTHAM CITY,GOTHAM CITY_13
14,PROBONO,CERNA Assessment,The neighbourhood is exploring a new approach ...,HOGSMEADE,HOGSMEADE_14
15,PROBONO,Green Roof,The town's skyline is set to become greener as...,HOGSMEADE,HOGSMEADE_15
16,CHRONICLE,Renovation planner,A digital tool that suports decision-making fo...,HOGSMEADE,HOGSMEADE_16
17,FORTESIE,Energy savings at municipal swimming pool,The municipal swimming pool has reopened after...,HOGSMEADE,HOGSMEADE_17
18,FORTESIE,Better air quality at schools,"At a school, air quality has quietly become pa...",HOGSMEADE,HOGSMEADE_18
19,EFORT,SecureBox in the Village Microgrid,A storm-prone rural community pilots a SecureB...,HOGSMEADE,HOGSMEADE_19
20,REEFLEX,The Digital Twin for Flexibility Empowerment,The local energy community is piloting a digit...,HOGSMEADE,HOGSMEADE_20

In [6]:
def getDesc(x,y):
    p = "Write a prompt for an image maker AI that would depict a visual for this following project:\n\n"+x+"\n\nMake sure the description matches the context of the fantasy setting of "+y+"."
    p += "\n\nAnswer only with the description, without any additional text."
    return brain.ask(p)

def getTitle(x,y):
    p = "Give a title to this project:\n\n"+x+"\n\nTry to have the title fit with the context of the fantasy setting of "+y+"."
    p += "\n\nAnswer only with the title, without any additional text; in up to 5-7 words"
    return brain.ask(p).replace('"',"").replace("**","").split(':')[-1].strip()

def getSummary(x,y):
    p = "You are a journalist and you want to write a press release or a newspaper article to this project:\n\n"+x+"\n\nTry to have the article fit with the context of the fantasy setting of "+y+"."
    p += "\n\nThe summary should be engaging and informative, highlighting the key aspects of the project.\n\n"
    p += "Avoid introductions like 'In a groundbreaking initiative,', 'The project aims to', or 'This innovative project' .. rather be friendly, using simple language a teenager could use."
    p += "\n\nAnswer only with the writing, without any additional text; in up to 200 words. Do not put styling, nor title, nor 'press release' tags for example"
    return brain.ask(p)

In [11]:
dfs["desc"] = dfs.apply(lambda row: getDesc(row["Text"], row["city"]), axis=1)
dfs["title"] = dfs.apply(lambda row: getTitle(row["Text"], row["city"]), axis=1)
dfs["summary"] = dfs.apply(lambda row: getSummary(row["Text"], row["city"]), axis=1)
dfs["IDPage"] = dfs.index + 10
dfs["cityOK"] = dfs.city.apply(lambda x: x.lower().replace(" city",""))
dfs

--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12
--- gpt-4o-mini:	 2025-11-09 11:37:12

,Project,Title,Text,city,ID,desc,title,summary,IDPage,cityOK
0,PROBONO,CERNA Assessment,The neighbourhood is exploring a new approach ...,SHIRE,SHIRE_0,"In a picturesque Shire-like setting, a vibrant...",Together for Tomorrow,The Shire is stepping up its game in the fight...,10,shire
1,PROBONO,Green Roof,The town's skyline is set to become greener as...,SHIRE,SHIRE_1,"A picturesque view of County Hall, a beautiful...",A Sustainable Skyline,County Hall is about to get a fresh new look! ...,11,shire
2,CHRONICLE,Renovation planner,A digital tool that suports decision-making fo...,SHIRE,SHIRE_2,"A serene landscape of the Shire, with quaint h...",Harmony in Renewal,A new digital tool is set to change how we thi...,12,shire
3,FORTESIE,Energy savings at municipal swimming pool,The municipal swimming pool has reopened after...,SHIRE,SHIRE_3,A picturesque scene of a Shire-inspired munici...,Renewed Comfort and Efficiency,The municipal swimming pool in Shire has offic...,13,shire
4,FORTESIE,Better air quality at schools,"At a school, air quality has quietly become pa...",SHIRE,SHIRE_4,In a picturesque Shire schoolhouse nestled amo...,Fresh Breezes for Bright Minds in Shire,"At Green Hollow School, breathing easy has tur...",14,shire
5,EFORT,SecureBox in the Village Microgrid,A storm-prone rural community pilots a SecureB...,SHIRE,SHIRE_5,A picturesque rural community in a fantasy Shi...,Enchanting Stability for Shire's Microgrid,A rural community in the stormy outskirts of S...,15,shire
6,REEFLEX,The Digital Twin for Flexibility Empowerment,The local energy community is piloting a digit...,SHIRE,SHIRE_6,A whimsical Shire landscape filled with quaint...,The Energy Harmony Nexus,"In the heart of SHIRE, a new digital tool is h...",16,shire
7,PROBONO,CERNA Assessment,The neighbourhood is exploring a new approach ...,GOTHAM CITY,GOTHAM CITY_7,"In a dark and moody rendition of Gotham City, ...",Bridging the Climate Divide in Gotham,Gotham City is stepping up its game in the bat...,17,gotham
8,PROBONO,Green Roof,The town's skyline is set to become greener as...,GOTHAM CITY,GOTHAM CITY_8,"Visualize a striking Gotham City skyline, wher...",Gotham's Sustainable Skyline Revolution,Gotham City is about to go green in a big way!...,18,gotham
9,CHRONICLE,Renovation planner,A digital tool that suports decision-making fo...,GOTHAM CITY,GOTHAM CITY_9,"Visualize a futuristic, high-tech digital dash...",Gotham's Energy Decision Tool,Gotham City is getting smarter with a new digi...,19,gotham
10,FORTESIE,Energy savings at municipal swimming pool,The municipal swimming pool has reopened after...,GOTHAM CITY,GOTHAM CITY_10,A vibrant scene set in Gotham City's newly ren...,Pool of Energy Efficiency,Gotham City’s municipal swimming pool is back ...,20,gotham
11,FORTESIE,Better air quality at schools,"At a school, air quality has quietly become pa...",GOTHAM CITY,GOTHAM CITY_11,"In a vibrant Gotham City school, a high-tech c...",Fresh Air Guardians of Gotham Academy,"At a school in Gotham, air quality is taking t...",21,gotham
12,EFORT,SecureBox in the Village Microgrid,A storm-prone rural community pilots a SecureB...,GOTHAM CITY,GOTHAM CITY_12,"A dark, stormy sky looms over a rugged rural c...",The Gotham Microgrid Shield,"In a stormy corner of Gotham City, a small rur...",22,gotham
13,REEFLEX,The Digital Twin for Flexibility Empowerment,The local energy community is piloting a digit...,GOTHAM CITY,GOTHAM CITY_13,"In the shadowy, neon-lit streets of Gotham Cit...",Gotham's Energy Revolution,"In Gotham City, residents are experiencing a n...",23,gotham
14,PROBONO,CERNA Assessment,The neighbourhood is exploring a new approach ...,HOGSMEADE,HOGSMEADE_14,Create an enchanting scene set in the whimsica...,Uniting for Change,Hogsmeade is stepping up to tackle climate cha...,24,hogsmeade
15,PROBONO,Green Roof,The town's skyline is set to become greener as...,HOGSMEADE,HOGSMEADE_15,Create an enchanting illustration of Hogsmeade...,Enchanting Rooftop Revolution at County Hall,Hogsmeade is about to get a stunning green mak...,25,hogsmeade
16,CHRONICLE,Renovation planner,A digital tool that suports decision-making fo...,HOGSMEADE,HOGSMEADE_16,"A whimsical scene set in Hogsmeade, showcasing...",Hogsmeade’s Sustainable Renovation Oracle,Imagine a magical tool that helps Hogsmeade ma...,26,hogsmeade
17,FORTESIE,Energy savings at municipal swimming pool,The municipal swimming pool has reopened after...,HOGSMEADE,HOGSMEADE_17,A whimsical illustration of the newly renovate...,A Magical Upgrade,The municipal swimming pool in Hogsmeade is ba...,27,hogsmeade
18,FORTESIE,Better air quality at schools,"At a school, air quality has quietly become pa...",HOGSMEADE,HOGSMEADE_18,"In a whimsical classroom set in Hogsmeade, the...",Hogsmeade's Classroom Revolution,"At Hogwarts School of Witchcraft and Wizardry,...",28,hogsmeade
19,EFORT,SecureBox in the Village Microgrid,A storm-prone rural community pilots a SecureB...,HOGSMEADE,HOGSMEADE_19,"In the quaint village of Hogsmeade, picturesqu...",SecureBox for Hogsmeade’s Power,"In the charming village of Hogsmeade, a new se...",29,hogsmeade
20,REEFLEX,The Digital Twin for Flexibility Empowerment,The local energy community is piloting a digit...,HOGSMEADE,HOGSMEADE_20,Create an enchanting scene set in Hogsmeade sh...,Hogsmeade's Enchanted Energy Nexus,Hogsmeade is buzzing with excitement as locals...,30,hogsmeade

In [ ]:
q = "medium"
q = "high"

q17 = """A whimsical illustration of the newly renovated municipal swimming pool in Hogsmeade, surrounded by quaint stone buildings covered in ivy. 
The pool is bustling with Hogwarts students, magical creatures, and townsfolk enjoying the refreshing water under a clear blue sky. 
Overhead, steam softly rises, indicating the newly installed heating system, while vibrant banners hang to display real-time energy savings, 
animated with magical sparkles. In the lobby, a group of excited visitors, including the headmaster and dean of hogwarts, engage in animated discussions 
about energy efficiency. Charming details like enchanted plants 
and playful house-elves add to the lively community atmosphere, highlighting the blend of practical upgrades 
and magical elements that enhance comfort and sustainability in this beloved town."""

for ix,row in dfs.iterrows():
    if not os.path.exists("images/"+row["ID"] + q+"_A4_landscape.png"):
        DESCRIPTION = row["desc"]
        if row["ID"] == "HOGSMEADE_17":
            print("Processing:", row["ID"])
            print(row["desc"])
            DESCRIPTION = q17
        if ix < 30:
            
            

            print("-- Image started for:", row["ID"])
            try:
                result = client.images.generate(
                    model="gpt-image-1",
                    prompt=DESCRIPTION,
                    size="1536x1024",
                    background="opaque",
                    quality=q,
                )
                print("-- Image generated for:", row["ID"])
                image_base64 = result.data[0].b64_json
                image_bytes = base64.b64decode(image_base64)
                with open("images/"+row["ID"] +q+".png", "wb") as f:
                    f.write(base64.b64decode(image_base64))

                # Load the image directly from bytes
                image = Image.open(BytesIO(image_bytes))

                # ---- A4 landscape ratio ----
                a4_ratio = 297 / 210  # ≈ 1.414

                # Compute new size keeping A4 ratio
                width, height = image.size
                if width / height > a4_ratio:
                    # Image is too wide → adjust width
                    new_width = int(height * a4_ratio)
                    new_height = height
                else:
                    # Image is too tall → adjust height
                    new_width = width
                    new_height = int(width / a4_ratio)

                # Resize (optional: change to a fixed A4 pixel size instead, e.g., 3508x2480)
                resized = image.resize((new_width, new_height), Image.LANCZOS)

                # Save the resized image
                resized.save("images/"+row["ID"] + q+"_A4_landscape.png", format="PNG")
            except:
                print("---- Image generation failed for:", row["ID"])

In [12]:
dfs.to_parquet("maptivity_cards_with_prompts.parquet.gzip", compression="gzip", index=False)

,Project,Title,Text,city,ID,desc,title,summary,IDPage,cityOK
0,PROBONO,CERNA Assessment,The neighbourhood is exploring a new approach ...,SHIRE,SHIRE_0,"In a picturesque Shire-like setting, a vibrant...",Together for Tomorrow,The Shire is stepping up its game in the fight...,10,shire
1,PROBONO,Green Roof,The town's skyline is set to become greener as...,SHIRE,SHIRE_1,"A picturesque view of County Hall, a beautiful...",A Sustainable Skyline,County Hall is about to get a fresh new look! ...,11,shire
2,CHRONICLE,Renovation planner,A digital tool that suports decision-making fo...,SHIRE,SHIRE_2,"A serene landscape of the Shire, with quaint h...",Harmony in Renewal,A new digital tool is set to change how we thi...,12,shire
3,FORTESIE,Energy savings at municipal swimming pool,The municipal swimming pool has reopened after...,SHIRE,SHIRE_3,A picturesque scene of a Shire-inspired munici...,Renewed Comfort and Efficiency,The municipal swimming pool in Shire has offic...,13,shire
4,FORTESIE,Better air quality at schools,"At a school, air quality has quietly become pa...",SHIRE,SHIRE_4,In a picturesque Shire schoolhouse nestled amo...,Fresh Breezes for Bright Minds in Shire,"At Green Hollow School, breathing easy has tur...",14,shire
5,EFORT,SecureBox in the Village Microgrid,A storm-prone rural community pilots a SecureB...,SHIRE,SHIRE_5,A picturesque rural community in a fantasy Shi...,Enchanting Stability for Shire's Microgrid,A rural community in the stormy outskirts of S...,15,shire
6,REEFLEX,The Digital Twin for Flexibility Empowerment,The local energy community is piloting a digit...,SHIRE,SHIRE_6,A whimsical Shire landscape filled with quaint...,The Energy Harmony Nexus,"In the heart of SHIRE, a new digital tool is h...",16,shire
7,PROBONO,CERNA Assessment,The neighbourhood is exploring a new approach ...,GOTHAM CITY,GOTHAM CITY_7,"In a dark and moody rendition of Gotham City, ...",Bridging the Climate Divide in Gotham,Gotham City is stepping up its game in the bat...,17,gotham
8,PROBONO,Green Roof,The town's skyline is set to become greener as...,GOTHAM CITY,GOTHAM CITY_8,"Visualize a striking Gotham City skyline, wher...",Gotham's Sustainable Skyline Revolution,Gotham City is about to go green in a big way!...,18,gotham
9,CHRONICLE,Renovation planner,A digital tool that suports decision-making fo...,GOTHAM CITY,GOTHAM CITY_9,"Visualize a futuristic, high-tech digital dash...",Gotham's Energy Decision Tool,Gotham City is getting smarter with a new digi...,19,gotham
10,FORTESIE,Energy savings at municipal swimming pool,The municipal swimming pool has reopened after...,GOTHAM CITY,GOTHAM CITY_10,A vibrant scene set in Gotham City's newly ren...,Pool of Energy Efficiency,Gotham City’s municipal swimming pool is back ...,20,gotham
11,FORTESIE,Better air quality at schools,"At a school, air quality has quietly become pa...",GOTHAM CITY,GOTHAM CITY_11,"In a vibrant Gotham City school, a high-tech c...",Fresh Air Guardians of Gotham Academy,"At a school in Gotham, air quality is taking t...",21,gotham
12,EFORT,SecureBox in the Village Microgrid,A storm-prone rural community pilots a SecureB...,GOTHAM CITY,GOTHAM CITY_12,"A dark, stormy sky looms over a rugged rural c...",The Gotham Microgrid Shield,"In a stormy corner of Gotham City, a small rur...",22,gotham
13,REEFLEX,The Digital Twin for Flexibility Empowerment,The local energy community is piloting a digit...,GOTHAM CITY,GOTHAM CITY_13,"In the shadowy, neon-lit streets of Gotham Cit...",Gotham's Energy Revolution,"In Gotham City, residents are experiencing a n...",23,gotham
14,PROBONO,CERNA Assessment,The neighbourhood is exploring a new approach ...,HOGSMEADE,HOGSMEADE_14,Create an enchanting scene set in the whimsica...,Uniting for Change,Hogsmeade is stepping up to tackle climate cha...,24,hogsmeade
15,PROBONO,Green Roof,The town's skyline is set to become greener as...,HOGSMEADE,HOGSMEADE_15,Create an enchanting illustration of Hogsmeade...,Enchanting Rooftop Revolution at County Hall,Hogsmeade is about to get a stunning green mak...,25,hogsmeade
16,CHRONICLE,Renovation planner,A digital tool that suports decision-making fo...,HOGSMEADE,HOGSMEADE_16,"A whimsical scene set in Hogsmeade, showcasing...",Hogsmeade’s Sustainable Renovation Oracle,Imagine a magical tool that helps Hogsmeade ma...,26,hogsmeade
17,FORTESIE,Energy savings at municipal swimming pool,The municipal swimming pool has reopened after...,HOGSMEADE,HOGSMEADE_17,A whimsical illustration of the newly renovate...,A Magical Upgrade,The municipal swimming pool in Hogsmeade is ba...,27,hogsmeade
18,FORTESIE,Better air quality at schools,"At a school, air quality has quietly become pa...",HOGSMEADE,HOGSMEADE_18,"In a whimsical classroom set in Hogsmeade, the...",Hogsmeade's Classroom Revolution,"At Hogwarts School of Witchcraft and Wizardry,...",28,hogsmeade
19,EFORT,SecureBox in the Village Microgrid,A storm-prone rural community pilots a SecureB...,HOGSMEADE,HOGSMEADE_19,"In the quaint village of Hogsmeade, picturesqu...",SecureBox for Hogsmeade’s Power,"In the charming village of Hogsmeade, a new se...",29,hogsmeade
20,REEFLEX,The Digital Twin for Flexibility Empowerment,The local energy community is piloting a digit...,HOGSMEADE,HOGSMEADE_20,Create an enchanting scene set in Hogsmeade sh...,Hogsmeade's Enchanted Energy Nexus,Hogsmeade is buzzing with excitement as locals...,30,hogsmeade

In [ ]:
import shutil

for ix, row in dfs.iterrows():
    fileApath = "images/"+row["city"]+"_"+str(row.IDPage - 10)+"high.png"
    fileBpath = "../docs/images/"+row["cityOK"]+'_activity_'+str(row["IDPage"])+".png"

    shutil.copyfile(fileApath, fileBpath)

In [17]:
# QR Codes

In [ ]:
import qrcode

for ix, row in dfs.iterrows():
    url = "http://maptivity.online/" #"http://maptivity.online/shire_activity_7.html"
    url += +str(row["cityOK"])+"_activity_"+str(row["IDPage"])+".html"
    # Create QR code
    qr = qrcode.QRCode(
        version=1,  # controls size; 1 is smallest
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=10,
        border=4,
    )

    qr.add_data(url)
    qr.make(fit=True)

    # Generate image
    img = qr.make_image(fill_color="black", back_color="white")

    # Save it
    img.save("qrcodes/"+str(row["IDPage"])+".png")

In [10]:

# Your data
texts = [
    "First text",
    "Second text",
    "Third text",
    "Fourth text",
    "Fifth text"
]
images = [
    "image1.jpg",
    "image2.jpg",
    "image3.jpg",
    "image4.jpg",
    "image5.jpg"
]

# Load the PowerPoint
ppt_path = "example.pptx"
prs = Presentation(ppt_path)

# Assume the first slide is the one we want to edit
slide = prs.slides[0]

# Blank layout index (usually 6)
blank_layout = prs.slide_layouts[6]

# Slide size for full-slide image
slide_width = prs.slide_width
slide_height = prs.slide_height

for text, image_path in zip(texts, images):
    # Edit text in the original slide
    for shape in slide.shapes:
        if shape.has_text_frame:
            shape.text = text
            break  # modify only the first text block

    # Add a blank slide and insert the image
    new_slide = prs.slides.add_slide(blank_layout)
    new_slide.shapes.add_picture(image_path, 0, 0, width=slide_width, height=slide_height)

# Save the updated PowerPoint
prs.save("updated_all.pptx")

PackageNotFoundError: Package not found at 'example.pptx'